// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAytCi75ceJM-odr26ZqtAAMRipAc-PeOk',
    appId: '1:362748504699:web:fc3e0faf8dceea063050de',
    messagingSenderId: '362748504699',
    projectId: 'baliza-ce864',
    authDomain: 'baliza-ce864.firebaseapp.com',
    storageBucket: 'baliza-ce864.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdS0JQjbDbw1tvnU8g63hHFCNJl6Mo-v0',
    appId: '1:362748504699:android:b18305f3c51543333050de',
    messagingSenderId: '362748504699',
    projectId: 'baliza-ce864',
    storageBucket: 'baliza-ce864.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7b9tkGj_Wd7mTEwUrYLobiRerIHlBov8',
    appId: '1:362748504699:ios:0d098832b75ca0e33050de',
    messagingSenderId: '362748504699',
    projectId: 'baliza-ce864',
    storageBucket: 'baliza-ce864.appspot.com',
    iosClientId: '362748504699-ctgom2u7dtior0m8ddajncc30n67qcdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.baliza',
  );
}
